apiVersion: apps/v1
kind: Deployment # To allow multiple pods
metadata:
  name: simpleapp
spec:
  replicas: 1 # Number of pods to run
  selector:
    matchLabels:
      app: simpleapp
  template:
    metadata:
      labels:
        app: simpleapp
    spec:
      containers:
      - name: simpleapp-container
        image: bistrulli/simpleapp
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m" # Recommended to use the m notation
          limits:
            memory: "256Mi"
            cpu: "1000m"
        ports:
        - containerPort: 80

