apiVersion: v1
kind: Service
metadata:
  name: deployedapp-service
  labels:
    app: busy-waiting-webapp
spec:
  selector:
    app: busy-waiting-webapp
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
  type: LoadBalancer

