apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: spring-test-app-tier2
  namespace: default  # Specify your namespace here if different
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spring-test-app-tier2
  minReplicas: 1
  maxReplicas: 100
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 15
      policies:
        - type: Pods
          value: 1
          periodSeconds: 120
