apiVersion: v1
kind: Service
metadata:
  name: deployedapp-service
  labels:
    app: my-prime-checker-app
spec:
  selector:
    app: my-prime-checker-app
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
  type: LoadBalancer

