apiVersion: v1
kind: Service
metadata:
  name: spring-test-app-tier1
  labels:
    app: spring-test-app
spec:
  selector:
    app: spring-test-app
    tier: tier1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

