apiVersion: apps/v1 # API version, v1 is stable for deployments
kind: Deployment    # To allow creation of pods
metadata:
  name: spring-test-app-tier1
spec:
  replicas: 1 # Number of pods to run
  selector:
    matchLabels:
      app: spring-test-app
      tier: tier1
  template:
    metadata:
      labels:
        app: spring-test-app
        tier: tier1
    spec:
      containers:
        - name: spring-test-app-tier1-container
          image: rpizziol/spring-test-app-tier1:0.27
          imagePullPolicy: Always
          resources:
            requests:
              memory: "1Gi"
              cpu: "1000m" # Recommended to use the m notation
            limits:
              memory: "1Gi"
              cpu: "16000m"
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 0 # Immediate probes
            periodSeconds: 20
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 2
          lifecycle:
            preStop:
              exec:
                command: [ "pkill", "-15", "-f", "k8testpod" ]

