apiVersion: apps/v1
kind: Deployment # To allow multiple pods
metadata:
  name: simpleapp
spec:
  replicas: 1 # Number of pods to run
  selector:
    matchLabels:
      app: simpleapp
  template:
    metadata:
      labels:
        app: simpleapp
    spec:
      containers:
      - name: simpleapp-container
        image: bistrulli/simpleapp
        ports:
        - containerPort: 80

