apiVersion: v1
kind: Service
metadata:
  name: my-prime-checker-app-service
spec:
  selector:
    app: my-prime-checker-app
    container-name: container-2 # Specify the container label
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
