apiVersion: v1
kind: Service
metadata:
  name: simpleapp-service
  labels:
    app: simpleapp
spec:
  selector:
    app: simpleapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer

