apiVersion: v1
kind: Service
metadata:
  name: custom-metrics-app-service
  labels:
    app: custom-metrics-app
spec:
  selector:
    app: custom-metrics-app
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
  type: LoadBalancer

